### ISSUE TITLE
Fail to run make bin

### ISSUE THREAD

**Issue by cristian98149** [mrizvic/dhcpmessage_exporter#1]
Hi,
The service doesn't start.

I get permission denied when I execute make bin :

[user1@machine1 dhcpmessage_exporter-main]$ make bin
env CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags "-X main.GitCommit=$(git rev-parse --short HEAD)" -o dhcpmessage_exporter-linux-amd64 . ;
fatal: Not a git repository (or any of the parent directories): .git
go: github.com/prometheus/client_golang@v1.11.0 requires
 github.com/json-iterator/go@v1.1.11: missing go.sum entry; to add it:
 go mod download github.com/json-iterator/go
go: github.com/prometheus/client_golang@v1.11.0 requires
 github.com/json-iterator/go@v1.1.11: missing go.sum entry; to add it:
 go mod download github.com/json-iterator/go
make: *** [bin] Error 1

**Comment by jumpswitch** [comment]
Try to fetch dependencies manually with `go mod tidy`
```
[~/dhcpmessage_exporter-main]$ go mod tidy
go: downloading github.com/prometheus/client_golang v1.8.0
go: downloading github.com/google/gopacket v1.1.19
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/common v0.14.0
go: downloading github.com/prometheus/procfs v0.2.0
go: downloading github.com/golang/protobuf v1.4.3
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/beorn7/perks v1.0.1
go: downloading golang.org/x/sys v0.0.0-20201015000850-e3ed0017c211
go: downloading golang.org/x/net v0.0.0-20200625001655-4c5254603344
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading google.golang.org/protobuf v1.23.0
go: downloading github.com/google/go-cmp v0.4.0
go: downloading golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
```
and run `make deps`
```
[~/dhcpmessage_exporter-main]$ make deps
go get -u -v github.com/google/gopacket
go: downloading github.com/google/gopacket v1.1.19
go get -u -v github.com/prometheus/client_golang 
go: downloading github.com/prometheus/client_golang v1.11.0
```

**Comment by cristian98149** [comment]
Hi, make deps is ok but make bin fails.

I tried to execute the service manually using "/usr/local/bin/dhcpmessage_exporter -promisc=false -interfaces="ens192" -listen-address=":8067" -debug" and everything worked, the service captured the dhcp packets ans sent them to prometheus/grafana.

But, I cannot start the service:
![image](https://user-images.githubusercontent.com/47886306/130797317-7977811e-9bbb-43ec-adf8-756e7f9ef6a8.png)

**Comment by cristian98149** [comment]
I think I found the cause:
![image](https://user-images.githubusercontent.com/47886306/130809687-853b8a94-2881-498b-b8f6-9753ff3d4d20.png)

The error seems to be due to the ens192 that cannot be found from the service.

**Comment by jumpswitch** [comment]
You must specify network interface adapter within `-interfaces` option.
For example if you run DHCP server on `eth1` then run with `-interfaces="eth1"`
Or if there are many interfaces then its like this `-interfaces="eth1 eth2 eth3"`

**Comment by cristian98149** [comment]
I've already specified it on systemd service:
![image](https://user-images.githubusercontent.com/47886306/130813671-970bf4c6-167d-40fe-a480-7196aeb008a6.png)

**Comment by jumpswitch** [comment]
Please show configuration for `ens192` interface.

Did you run `setcap` ?
```
setcap cap_net_raw,cap_net_admin=eip /usr/local/bin/dhcpmessage_exporter
```

**Comment by cristian98149** [comment]
Sure, and as you can see, seems that the command worked:

![image](https://user-images.githubusercontent.com/47886306/130815257-45e1227c-627f-4bbc-9a50-5ff1d3e6978f.png)

**Comment by jumpswitch** [comment]
```
pcap.OpenLive() ERROR:ens192: No such device exists (SIOCGIFHWADDR: No such device)
```
This means that network interface `ens192` does not exist.

**Comment by cristian98149** [comment]
The interface exists as you can see:
![image](https://user-images.githubusercontent.com/47886306/130817344-4a4aa34f-cff8-40ea-8f32-e77910d03783.png)


Anyway, as I said in previous comment, if I run manually "/usr/local/bin/dhcpmessage_exporter -interfaces=ens192 -listen-address=":8067" -promisc=false" everything work correctly. The issue is just on the service.

**Comment by jumpswitch** [comment]
I tried to reproduce on fresh RHEL 8.4 machine and my error message was this (since I dont have ens192 device):
```
interfaces=ens192
pcap.OpenLive() ERROR:ens192: No such device exists (SIOCGIFHWADDR: No such device)
```
However from your screenshot above the error message looks like this:
```
interfaces="ens192"
pcap.OpenLive() ERROR:"ens192": No such device exists (SIOCGIFHWADDR: No such device)
```

From this I assume something is wrong with quotes in your `/etc/systemd/system/dhcpmessage_exporter.service` file.
Since you have only one interface you can write argument without quotes:
```
ExecStart=/usr/local/bin/dhcpmessage_exporter -promisc="false" -interfaces=ens192 -listen-address=":8067"
```

**Comment by cristian98149** [comment]
I found the cause:
the double quotes on -listen-address were the issue.

now the string on my service script is:
_ExecStart=/usr/local/bin/dhcpmessage_exporter -interfaces=ens192 -listen-address=0.0.0.0:8067 -promisc=false_

and the service is running.

Thank you!!
